// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Opsi konfigurasi default [FirebaseOptions] untuk menghubungkan aplikasi Flutter
/// dengan proyek Firebase berdasarkan target platform (Web, Android, iOS, dll).
///
/// Contoh Penggunaan:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Mengembalikan konfigurasi [FirebaseOptions] yang sesuai dengan platform target saat runtime.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKRHyahTNdJo01aZOURPgsbGKiX5ViCY8',
    appId: '1:130515174634:web:6f7ffd8529875e5bd30393',
    messagingSenderId: '130515174634',
    projectId: 'phintar-edu-6cd66',
    authDomain: 'phintar-edu-6cd66.firebaseapp.com',
    storageBucket: 'phintar-edu-6cd66.firebasestorage.app',
    measurementId: 'G-EYGD5YSF4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4DT-vj60_QT_CM_mxeP09IOdepAkOSCo',
    appId: '1:130515174634:android:e18b05e0665eab00d30393',
    messagingSenderId: '130515174634',
    projectId: 'phintar-edu-6cd66',
    storageBucket: 'phintar-edu-6cd66.firebasestorage.app',
  );
}
